s dbaseURL: https://neelmalhotra.netlify.app
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Let's dive in
    subtitle: |-
      I am a swimmer from India, currently pursuing the MSc Financial Analysis at LBS.
    title: Welcome, my name is Neel Malhotra.
  blog: {}
  contact:
    address:
      - city: London, NW8 8TJ
        country: United Kingdom
        street: London Business School(LBS)
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: nmalhotra.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 7878839506
        title: Phone Number
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Neel Malhotra
    enable: yes
    quicklinks:
    social:
      - icon: Wapplogo.jpg
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: LBSphwl.jpg
        subtitle: A short biography
        title: About Neel
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: ipsum
        url: blogs/ipsum
   
  #two:
   # buttonText: Get Started
    #enable: yes
    #subtitle: "Hi guys, thanks for going through my website. If you would like to connect over a cup of coffee, please find below my contact information"
    #title: Thank you!
    #url: blogs
